/**
 * Airline knowledge base.
 * ALWAYS the real IATA code. NEVER derived from the first letters of the name.
 * American Airlines = AA (never AM), Air Serbia = JU (never AI),
 * British Airways = BA (never BR), Egyptair = MS (never EG).
 */

// name (lowercased, normalized) -> IATA code
const NAME_TO_CODE: Record<string, string> = {
  // --- spec-critical carriers ---
  "american airlines": "AA",
  american: "AA",
  "air serbia": "JU",
  "british airways": "BA",
  "air canada": "AC",
  "air canada rouge": "AC",
  egyptair: "MS",
  "egypt air": "MS",
  "united airlines": "UA",
  united: "UA",
  "delta air lines": "DL",
  delta: "DL",
  lufthansa: "LH",
  "air france": "AF",
  klm: "KL",
  "klm royal dutch airlines": "KL",
  "qatar airways": "QR",
  emirates: "EK",
  "turkish airlines": "TK",
  etihad: "EY",
  "etihad airways": "EY",
  // --- north america ---
  "alaska airlines": "AS",
  alaska: "AS",
  "allegiant air": "G4",
  allegiant: "G4",
  "american eagle": "AA",
  "breeze airways": "MX",
  breeze: "MX",
  "frontier airlines": "F9",
  frontier: "F9",
  "hawaiian airlines": "HA",
  hawaiian: "HA",
  "jetblue": "B6",
  "jetblue airways": "B6",
  "southwest airlines": "WN",
  southwest: "WN",
  "spirit airlines": "NK",
  spirit: "NK",
  "sun country airlines": "SY",
  "sun country": "SY",
  "westjet": "WS",
  "westjet airlines": "WS",
  "porter airlines": "PD",
  porter: "PD",
  "flair airlines": "F8",
  flair: "F8",
  "aeromexico": "AM",
  "aero mexico": "AM",
  "avianca": "AV",
  "copa airlines": "CM",
  copa: "CM",
  "azul linhas aereas": "AD",
  azul: "AD",
  "gol linhas aereas": "G3",
  gol: "G3",
  "latam airlines": "LA",
  latam: "LA",
  "aerolineas argentinas": "AR",
  // --- europe ---
  "air europe": "UX",
  "air lingus": "EI",
  "air malta": "KM",
  "air moldova": "9U",
  "air nostrum": "YW",
  "air baltic": "BT",
  "austrian airlines": "OS",
  austrian: "OS",
  "brussels airlines": "SN",
  brussels: "SN",
  "bulgaria air": "FB",
  "croatia airlines": "OU",
  croatia: "OU",
  "cyprus airways": "CY",
  "czech airlines": "OK",
  "easyjet": "U2",
  "easy jet": "U2",
  "finnair": "AY",
  "iberia express": "I2",
  "iberia": "IB",
  "icelandair": "FI",
  "iceland air": "FI",
  "ita airways": "AZ",
  "lot polish airlines": "LO",
  lot: "LO",
  "luxair": "LG",
  "lufthansa city airlines": "CL",
  "discover airlines": "4Y",
  "lufthansa discover": "4Y",
  "norwegian air shuttle": "DY",
  norwegian: "DY",
  "play airlines": "OG",
  "ryanair": "FR",
  "ryan air": "FR",
  "sas scandinavian airlines": "SK",
  "scandinavian airlines": "SK",
  sas: "SK",
  "swiss international air lines": "LX",
  "swiss international airlines": "LX",
  swiss: "LX",
  "tap air portugal": "TP",
  "tap portugal": "TP",
  tap: "TP",
  "tarom": "RO",
  "tui airways": "BY",
  "turkish air": "TK",
  "vueling": "VY",
  "wizz air": "W6",
  "wizz air uk": "W9",
  "wideroe": "WF",
  "transavia": "HV",
  "transavia france": "TO",
  "eurowings": "EW",
  "aegan airlines": "A3",
  aegean: "A3",
  "air albania": "ZB",
  "carpatair": "V3",
  "smartwings": "QS",
  "korean air": "KE",
  // --- middle east / africa ---
  "egyptair express": "MS",
  "ethiopian airlines": "ET",
  ethiopian: "ET",
  "ethiopian air": "ET",
  "kenya airways": "KQ",
  kenya: "KQ",
  "royal air maroc": "AT",
  "royal jordanian": "RJ",
  "middle east airlines": "ME",
  "saudi arabian airlines": "SV",
  saudia: "SV",
  "gulf air": "GF",
  "oman air": "WY",
  "kuwait airways": "KU",
  "kuwait": "KU",
  "israel airways": "LY",
  "el al": "LY",
  "air arabia": "G9",
  "flydubai": "FZ",
  "fly dubai": "FZ",
  "south african airways": "SA",
  "air seychelles": "HM",
  "rwandair": "WB",
  "air mauritius": "MK",
  "tunisair": "TU",
  "air algerie": "AH",
  "air senegal": "HC",
  // --- asia / pacific ---
  "air india": "AI",
  "air india express": "IX",
  "all nippon airways": "NH",
  "ana": "NH",
  "japan airlines": "JL",
  "japan air lines": "JL",
  jal: "JL",
  "cathay pacific": "CX",
  cathay: "CX",
  "singapore airlines": "SQ",
  "malaysia airlines": "MH",
  "thai airways": "TG",
  "thai airways international": "TG",
  "vietnam airlines": "VN",
  "vietjet air": "VJ",
  vietjet: "VJ",
  "philippine airlines": "PR",
  "philippines airasia": "P2",
  "cebu pacific": "5J",
  "cebu pacific air": "5J",
  "garuda indonesia": "GA",
  garuda: "GA",
  "lion air": "JT",
  "batik air": "ID",
  "airasia": "AK",
  "air asia": "AK",
  "airasia x": "D7",
  "air asia x": "D7",
  "indigo": "6E",
  "indigo airlines": "6E",
  "vistara": "UK",
  "spicejet": "SG",
  "spice jet": "SG",
  "go first": "G8",
  "akasa air": "QP",
  "china airlines": "CI",
  "china eastern airlines": "MU",
  "china eastern": "MU",
  "china southern airlines": "CZ",
  "china southern": "CZ",
  "air china": "CA",
  "hainan airlines": "HU",
  "xiamen airlines": "MF",
  "xiamenair": "MF",
  "sichuan airlines": "3U",
  "shenzhen airlines": "ZH",
  "shandong airlines": "SC",
  "cathay dragon": "KA",
  "hong kong airlines": "HX",
  "eva air": "BR",
  "eva airways": "BR",
  "starlux airlines": "JX",
  "tigerair taiwan": "IT",
  "korean air lines": "KE",
  "asiana airlines": "OZ",
  asiana: "OZ",
  "jeju air": "7C",
  "air premia": "YP",
  "air new zealand": "NZ",
  "qantas": "QF",
  "qantas airways": "QF",
  "virgin australia": "VA",
  "virgin atlantic": "VS",
  "virgin atlantic airways": "VS",
  "fiji airways": "FJ",
  "fiji": "FJ",
  "air tahiti nui": "TN",
  "air pacific": "FJ",
  "biman bangladesh airlines": "BG",
  "srilankan airlines": "UL",
  "sri lankan airlines": "UL",
  "nepal airlines": "RA",
  "uzbekistan airways": "HY",
  "air astana": "KC",
  "azerbaijan airlines": "J2",
  "georgian airways": "A9",
  "pakistan international airlines": "PK",
  "cambodia angkor air": "K6",
  "myanmar airways international": "8M",
  "mongolian airlines": "OM",
  // --- latin / others ---
  "volaris": "Y4",
  "volaris costa rica": "Q6",
  "vivaaerobus": "VB",
  "viva aerobus": "VB",
  "jetSMART": "JA",
  "skymark airlines": "BC",
  "scoot": "TR",
  "scoot airlines": "TR",
  "jetstar japan": "GK",
  // bare "Jetstar" on Japanese itineraries resolves to Jetstar Japan (GK)
  jetstar: "GK",
  "jetstar airways": "JQ",
  "jetstar asia": "3K",
  "jetstar pacific": "BL",
  "air asia japan": "DJ",
  "peach aviation": "MM",
  "zipair tokyo": "ZG",
  "solaseed air": "6J",
  "starflyer": "7G",
  "bamboo airways": "QH",
};

// Active IATA two-letter codes allowed for bare "XX 1234" flight detection
const CODES = new Set<string>([
  "AA", "AC", "AD", "AE", "AF", "AH", "AI", "AM", "AR", "AS", "AT", "AV", "AY", "AZ",
  "B6", "BA", "BG", "BI", "BL", "BR", "BT", "BY",
  "CA", "CI", "CM", "CX", "CY", "CZ",
  "D7", "DE", "DL", "DY",
  "EI", "EK", "ET", "EW", "EY", "E7",
  "F8", "F9", "FI", "FJ", "FR", "FZ",
  "G3", "G4", "G8", "G9", "GA", "GF", "GJ", "GK",
  "HU", "HX", "HY",
  "I2", "IB", "ID",
  "J2", "JL", "JQ", "JT", "JU", "JX",
  "KA", "KC", "KE", "KM", "KQ", "KU", "K6",
  "LA", "LG", "LH", "LO", "LX", "LY",
  "ME", "MF", "MH", "MK", "MM", "MU", "MX",
  "NH", "NK", "NZ",
  "OG", "OK", "OM", "OS", "OU", "OZ",
  "P2", "PD", "PK", "PR",
  "QF", "QP", "QR", "QS",
  "RA", "RJ", "RO",
  "SA", "SC", "SG", "SK", "SN", "SQ", "SU", "SV", "SY",
  "TG", "TK", "TN", "TP", "TR", "TU", "T5",
  "U2", "UA", "UL", "UX",
  "VA", "VB", "VN", "VS", "VJ", "VY",
  "W6", "WB", "WF", "WN", "WS", "WY",
  "Y4", "Y8", "ZB", "ZG", "ZH",
  "3U", "3K", "4Y", "5J", "6E", "6J", "7C", "7M", "8M", "9U", "9W",
  "A3", "B6", "D7", "F8", "F9", "G3", "G4", "G8", "G9", "J2", "K6", "P2", "Q6", "T5", "U2", "W6", "Y4", "Y8",
]);

export interface AirlineMatch {
  code: string;
  /** length of matched name text */
  nameLen: number;
}

const NAME_KEYS = Object.keys(NAME_TO_CODE).sort((a, b) => b.length - a.length);

/** Resolve an airline name (case insensitive) to an IATA code. */
export function airlineFromName(name: string): string | null {
  const n = name.toLowerCase().replace(/[^a-z ]/g, " ").replace(/\s+/g, " ").trim();
  if (!n) return null;
  for (const key of NAME_KEYS) {
    if (n === key) return NAME_TO_CODE[key];
  }
  return null;
}

export function isAirlineCode(code: string): boolean {
  return CODES.has(code);
}

/** Normalized airline names (lowercase, longest first) for regex iteration */
export const AIRLINE_NAMES: string[] = NAME_KEYS;

export function isValidAirlineCode(code: string): boolean {
  return /^[A-Z]{2}$/.test(code) && CODES.has(code);
}
